[Service]
ProtectKernelModules=true
ProtectHostname=true
ProtectClock=true
ProtectKernelLogs=true
RestrictNamespaces=true
SystemCallFilter=@system-service
SystemCallFilter=~@privileged @resources
CapabilityBoundingSet=
AmbientCapabilities=
UMask=0077
