[Service]
ExecStart=
ExecStart=/usr/bin/hblock -S /home/panda/.config/hblock/sources.list -A /home/panda/.config/hblock/allow.list -O /etc/hosts -F /home/panda/.config/hblock/footer.list
PrivateTmp=true
NoNewPrivileges=true
# Need to read lists from panda's home
ProtectHome=read-only
ProtectSystem=strict
ReadWritePaths=/etc/hosts
ProtectKernelTunables=true
ProtectKernelModules=true
ProtectControlGroups=true
RestrictSUIDSGID=true
LockPersonality=true
RestrictRealtime=true
SystemCallArchitectures=native
