# --- Virtual Memory (128GB RAM Tuning) ---
vm.swappiness = 1              # Only swap as a last resort
vm.vfs_cache_pressure = 50     # Keep file metadata in RAM longer
vm.dirty_ratio = 10            # Start flushing to disk at 10% dirty (12.8GB)
vm.dirty_background_ratio = 3  # Background flush at 3% (3.8GB)
vm.max_map_count = 2147483647  # Vital for heavy games (Star Citizen, etc.)

# --- Network (High Speed / Low Latency) ---
# net.core.default_qdisc = fq # TODO: Check this setting, I don't think this is exposed anymore?
net.ipv4.tcp_congestion_control = bbr
net.ipv4.tcp_fastopen = 3

# --- 7900X3D Scheduler Tweaks ---
# Lowering these values makes the scheduler more aggressive/responsive
# kernel.sched_migration_cost_ns = 500000 # TODO: Check this setting, I don't think this is exposed anymore?
kernel.sched_autogroup_enabled = 0
